---
- name: 'Import validator tasks'
  ansible.builtin.import_tasks: validator/main.yml

- name: 'INCLUDE => User management tasks'
  loop: "{{ user_list | dict2items }}"
  ansible.builtin.include_tasks: processing/main.yml
