---
- name: 'Import validator tasks'
  ansible.builtin.import_tasks: validator/main.yml

- name: 'INCLUDE => User management tasks'
  loop: "{{ user_list | dict2items }}"
  tags:
    - users
  ansible.builtin.include_tasks:
    file: processing/main.yml
    apply:
      tags:
        - users

