---
- name: 'import validator tasks'
  ansible.builtin.import_tasks: validator/main.yml

- name: 'INCLUDE => user management tasks'
  ansible.builtin.include_tasks: processing/main.yml
  loop: "{{ user_list | dict2items }}"
