---
- name: 'processing | authorized_keys | deploy ssh authorized_keys for user {{ user }}'
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: "{{ data.value.state }}"
    key: "{{ data.value.content }}"
    key_options: "{{ data.value.opts }}"
