---
- name: 'Processing | User_creation | Manage user {{ user.key }}'
  ansible.builtin.user:
    name: "{{ user.key }}"
    comment: "{{ user['value']['comment'] }}"
    createhome: true
    home: "{{ user['value']['home'] }}"
    shell: "{{ user['value']['shell'] }}"
    state: "{{ user['value']['state'] }}"
    password: "{{ passwd }}"
    update_password: always

- name: 'Processing | User_creation | Ensure home directory rights'
  ansible.builtin.file:
    path: "{{ user['value']['home'] }}"
    owner: "{{ user.key }}"
    group: "{{ user.key }}"
    state: directory
    recurse: yes
